In [17]:
import numpy as np
import pandas as pd

In [18]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits= pd.read_csv('tmdb_5000_credits.csv')

In [19]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [20]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [21]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [22]:
credits.head(1).values

array([[19995, 'Avatar',
        '[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]',

In [23]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
movies.shape

(4803, 20)

In [25]:
credits.shape

(4803, 4)

In [26]:
movies = movies.merge(credits,on = 'title')

In [27]:
movies.shape

(4809, 23)

In [28]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [29]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [30]:
movies['original_language'].value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: count, dtype: int64

In [31]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

movies= movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [33]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [34]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [35]:
movies.dropna(inplace=True)

In [36]:
movies.duplicated().sum()

0

In [37]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [38]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [39]:
movies['genres']= movies['genres'].apply(convert)

In [40]:
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [41]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [42]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [43]:
movies['keywords'] = movies['keywords'].apply(convert)

In [44]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [45]:
movies['cast']

0       [{"cast_id": 242, "character": "Jake Sully", "...
1       [{"cast_id": 4, "character": "Captain Jack Spa...
2       [{"cast_id": 1, "character": "James Bond", "cr...
3       [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       [{"cast_id": 5, "character": "John Carter", "c...
                              ...
4804    [{"cast_id": 1, "character": "El Mariachi", "c...
4805    [{"cast_id": 1, "character": "Buzzy", "credit_...
4806    [{"cast_id": 8, "character": "Oliver O\u2019To...
4807    [{"cast_id": 3, "character": "Sam", "credit_id...
4808    [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4806, dtype: object

In [46]:
import ast
def convert3(obj):
    L=[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter = counter+1
        else:
            break
    return L

In [47]:
movies['cast'] = movies['cast'].apply(convert3)

In [48]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [49]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [50]:
import ast
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
           L.append(i['name'])
           break
    return L

In [51]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [52]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [53]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [54]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [55]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [56]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace("  "," ")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace("  "," ")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace("  "," ")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace("  "," ")for i in x])

In [57]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [58]:
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [59]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [60]:
movies['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'Science Fiction',
 'culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d',
 'Sam Worthington',
 'Zoe Saldana',
 'Sigourney Weaver',
 'James Cameron']

In [61]:
new_df = movies[['movie_id','title','tags']]

In [62]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [63]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\swapn\AppData\Local\Temp\ipykernel_4836\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [64]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [65]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\swapn\AppData\Local\Temp\ipykernel_4836\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [66]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [67]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy science fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d sam worthington zoe saldana sigourney weaver james cameron'

In [68]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drug abuse exotic island east india trading company love of one's life traitor shipwreck strong woman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnny depp orlando bloom keira knightley gore verbinski"

In [69]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [70]:
Vectors = cv.fit_transform(new_df['tags']).toarray()

In [71]:
Vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [72]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'], dtype=object)

In [73]:
import nltk

In [74]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [75]:
ps.stem('loving')

'love'

In [76]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [77]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\swapn\AppData\Local\Temp\ipykernel_4836\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [78]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [79]:
from sklearn.metrics.pairwise import cosine_similarity

In [80]:
similarity = cosine_similarity(Vectors)

In [81]:
similarity[2]

array([0.04948717, 0.04259177, 1.        , ..., 0.01944039, 0.08924215,
       0.        ])

In [82]:
similarity[0]

array([1.        , 0.06885304, 0.04948717, ..., 0.03142697, 0.05410018,
       0.        ])

In [83]:
sorted(similarity[0],reverse = True)

[0.9999999999999991,
 0.4839354795704658,
 0.4335521648830699,
 0.4278406467922595,
 0.398216086792002,
 0.3920784235278427,
 0.3841143835488626,
 0.3829708431025352,
 0.3703280399090205,
 0.3618136134933163,
 0.3500700210070024,
 0.34641016151377535,
 0.3429285639896449,
 0.34286375654996765,
 0.33975790709773834,
 0.33626912299068296,
 0.32118202741878643,
 0.3202563076101742,
 0.32005290567945544,
 0.3197221015541812,
 0.31843917593777593,
 0.3175426480542941,
 0.31035207097778317,
 0.30792014356780034,
 0.30772872744833174,
 0.3058211406170429,
 0.30135960257289474,
 0.30076824709656186,
 0.2933333333333333,
 0.29328528800913556,
 0.29059326290271154,
 0.2833333333333333,
 0.28323527714997326,
 0.28323527714997326,
 0.2809757434745082,
 0.28097574347450816,
 0.2790727860929737,
 0.27529888064467406,
 0.27487370837451064,
 0.27005424071710654,
 0.2684624220856097,
 0.26468964101491776,
 0.26222491255009456,
 0.2618614682831908,
 0.2613098319673951,
 0.2613098319673951,
 0.2587046667054218,
 0.25855725062711327,
 0.2578013546541959,
 0.2570358257720839,
 0.2550393009813292,
 0.25002164408471217,
 0.24886840673530208,
 0.24886840673530203,
 0.24743582965269673,
 0.24731360893412466,
 0.24731360893412463,
 0.2468365249354197,
 0.24377011365784199,
 0.2405267289609052,
 0.24019223070763068,
 0.23791547571544322,
 0.2333333333333333,
 0.23190036174568107,
 0.23145502494313783,
 0.22819305877276824,
 0.22721502297750173,
 0.2267786838055363,
 0.2257105970747514,
 0.22417941532712196,
 0.2236067977499789,
 0.22205444400108035,
 0.21602468994692864,
 0.21469801604867725,
 0.21213203435596426,
 0.20889318714683738,
 0.20889318714683738,
 0.20604887854797269,
 0.20412414523193145,
 0.20402454818026822,
 0.2036700308869262,
 0.20272121351984576,
 0.2021164610559645,
 0.20207259421636903,
 0.20083160441856088,
 0.19999999999999993,
 0.19882696935448685,
 0.19882696935448685,
 0.1986798535597565,
 0.19794866372215736,
 0.19794866372215736,
 0.1963961012123931,
 0.1951800145897066,
 0.1951800145897066,
 0.19518001458970655,
 0.19461345311993636,
 0.19379255804998172,
 0.19157898882855987,
 0.19033238057235458,
 0.18856180831641267,
 0.18856180831641264,
 0.18727643676692465,
 0.18683974659876548,
 0.18665130505147653,
 0.18527342263463414,
 0.1838509439481975,
 0.1835325870964494,
 0.18257418583505536,
 0.18187954468925663,
 0.1811643254631353,
 0.1811643254631353,
 0.18090680674665816,
 0.18039504672067896,
 0.17888543819998312,
 0.1756620131307359,
 0.17457431218879385,
 0.17432038578211329,
 0.17407765595569782,
 0.17320508075688773,
 0.1732050807568877,
 0.1732050807568877,
 0.1732050807568877,
 0.17284832429004493,
 0.17232808737106578,
 0.1718675697694639,
 0.17126976771553504,
 0.17126976771553504,
 0.17126976771553504,
 0.1710674406895399,
 0.1708484392354498,
 0.1708484392354498,
 0.17056057308448833,
 0.1702513061517497,
 0.16973368495830107,
 0.16854019432007686,
 0.16666666666666666,
 0.16536212616062237,
 0.16495721976846445,
 0.16431676725154984,
 0.16413890689295377,
 0.16397831834998455,
 0.1632993161855452,
 0.16329931618554516,
 0.16329931618554516,
 0.1621769708158766,
 0.16169041669088863,
 0.16165807537309518,
 0.1613118265234886,
 0.16035674514745463,
 0.16035674514745463,
 0.15894388284780522,
 0.15851878478024337,
 0.15842360687626786,
 0.15713484026367722,
 0.15713484026367722,
 0.15713484026367722,
 0.15701620314577236,
 0.15666989036012804,
 0.15666989036012804,
 0.15614401167176528,
 0.15491933384829665,
 0.15491933384829665,
 0.15430334996209188,
 0.1539600717839002,
 0.15322617553657472,
 0.15322617553657472,
 0.15320646925708528,
 0.15291057030852145,
 0.15275252316519464,
 0.1518652793203998,
 0.15163507931514908,
 0.1515873457919734,
 0.15118578920369086,
 0.15074151616205692,
 0.15032920560056579,
 0.15009575487729127,
 0.15,
 0.14985372985307102,
 0.14985372985307102,
 0.14969103983674978,
 0.14907119849998596,
 0.14907119849998593,
 0.14907119849998593,
 0.14907119849998593,
 0.14792005232672772,
 0.14784425419091457,
 0.14770978917519925,
 0.14770978917519925,
 0.14770978917519922,
 0.14765433214708534,
 0.14687761472690508,
 0.14552137502179976,
 0.14517323726225953,
 0.14474937289114914,
 0.14433756729740646,
 0.14426714154678916,
 0.14426714154678913,
 0.14381849910133493,
 0.14290535654155878,
 0.14288690166235202,
 0.14288690166235202,
 0.14253932901995964,
 0.1414213562373095,
 0.1411300658019085,
 0.14026687687393438,
 0.14012980994907412,
 0.13926212476455826,
 0.13926212476455826,
 0.13900960937138315,
 0.1388730149658827,
 0.13862065601673437,
 0.13856406460551016,
 0.13856406460551016,
 0.13770607453181924,
 0.13764944032233703,
 0.13696601740023184,
 0.1366260102127946,
 0.1366260102127946,
 0.13645764784420258,
 0.13645764784420258,
 0.13620104492139976,
 0.136176581329838,
 0.13617658132983798,
 0.13608276348795434,
 0.1352962850405092,
 0.1352962850405092,
 0.1352962850405092,
 0.13474430737064302,
 0.1333333333333333,
 0.1330598287718231,
 0.13288211940534983,
 0.13288211940534983,
 0.13196577581477156,
 0.13112201362143713,
 0.13093073414159542,
 0.13074409009212265,
 0.13063945294843615,
 0.12943004578588677,
 0.1293523333527109,
 0.12909944487358055,
 0.12865350418053537,
 0.1281025230440697,
 0.1281025230440697,
 0.1281025230440697,
 0.12792042981336624,
 0.12780193008453875,
 0.12751534261266764,
 0.12701705922171763,
 0.12696221085454767,
 0.12674485010489556,
 0.12649110640673514,
 0.12649110640673514,
 0.1262337488534405,
 0.1259673314595547,
 0.1259673314595547,
 0.12570787221094176,
 0.12510864843424482,
 0.12455983106584366,
 0.1245504737559055,
 0.12451456127293804,
 0.12443420336765101,
 0.12333396776895567,
 0.12326312688558731,
 0.12239801227242089,
 0.1223550580642996,
 0.12235505806429958,
 0.12185435916898847,
 0.12185435916898847,
 0.1217161238900369,
 0.12129568697262451,
 0.12060453783110545,
 0.12060453783110543,
 0.12049281521534184,
 0.12038585308576918,
 0.12026336448045262,
 0.11999999999999997,
 0.11925695879998875,
 0.11925695879998875,
 0.11925695879998875,
 0.11917591430622479,
 0.1188177051572009,
 0.11790126894931265,
 0.11790126894931265,
 0.11790126894931263,
 0.11731769201708263,
 0.11731769201708263,
 0.11724207635210981,
 0.11710800875382396,
 0.11710800875382396,
 0.11547005383792516,
 0.11547005383792515,
 0.11547005383792514,
 0.11547005383792514,
 0.11547005383792512,
 0.11457837984630925,
 0.11430952132988163,
 0.11389895949029986,
 0.11377602479771486,
 0.11338934190276813,
 0.11322770341445956,
 0.11322770341445956,
 0.11322770341445956,
 0.11318329168362204,
 0.11318329168362204,
 0.11318329168362204,
 0.11285529853737572,
 0.1128552985373757,
 0.1128552985373757,
 0.1128552985373757,
 0.11239029738980326,
 0.11239029738980326,
 0.11239029738980326,
 0.11208970766356098,
 0.11208970766356098,
 0.11202240672224077,
 0.11202240672224077,
 0.11202240672224076,
 0.11202240672224076,
 0.11202240672224076,
 0.11202240672224076,
 0.11202240672224076,
 0.11120768749710652,
 0.11120768749710652,
 0.11111111111111112,
 0.1111111111111111,
 0.11102722200054017,
 0.11102722200054017,
 0.11094003924504581,
 0.11094003924504581,
 0.11041048949477665,
 0.10999438818457405,
 0.10999438818457405,
 0.10963019357240503,
 0.1095445115010332,
 0.10910894511799615,
 0.1089898521826132,
 0.1089898521826132,
 0.10894095588038442,
 0.10886621079036349,
 0.10886621079036347,
 0.10886621079036347,
 0.10886621079036346,
 0.10886621079036346,
 0.10886621079036346,
 0.10820035616009187,
 0.10820035616009187,
 0.10820035616009185,
 0.10820035616009185,
 0.10820035616009185,
 0.10811798054391773,
 0.10801234497346432,
 0.10721125348377948,
 0.10721125348377948,
 0.10721125348377947,
 0.10706067580626215,
 0.10706067580626215,
 0.10690449676496976,
 0.10690449676496974,
 0.10690449676496974,
 0.10690449676496974,
 0.10690449676496974,
 0.10613372610104645,
 0.10613372610104645,
 0.10613372610104645,
 0.10613372610104645,
 0.10596258856520348,
 0.10565410875907484,
 0.10551786871689885,
 0.10540925533894595,
 0.10540925533894595,
 0.10540925533894595,
 0.10527227119356301,
 0.10523044392039604,
 0.10459527207369812,
 0.10444659357341869,
 0.10444659357341869,
 0.10444659357341869,
 0.10444659357341869,
 0.10434983894999016,
 0.10434983894999016,
 0.10434983894999016,
 0.10393116839386093,
 0.10393116839386092,
 0.10369516947304251,
 0.10369516947304251,
 0.10327955589886444,
 0.10327955589886444,
 0.10327955589886444,
 0.1026529805149473,
 0.10215078369104982,
 0.10215078369104982,
 0.10206207261596573,
 0.1018350154434631,
 0.10183501544346309,
 0.10141851056742197,
 0.10105823052798227,
 0.10105823052798227,
 0.10103629710818449,
 0.10103629710818449,
 0.10103629710818449,
 0.10079052613579391,
 0.10079052613579391,
 0.1005037815259212,
 0.1005037815259212,
 0.1005037815259212,
 0.1005037815259212,
 0.1002560823655206,
 0.1001958865736239,
 0.10012523486435175,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09949366763261819,
 0.09949366763261819,
 0.09903751369442765,
 0.09901475429766741,
 0.09901475429766741,
 0.09901475429766741,
 0.09901475429766741,
 0.09901475429766741,
 0.09897433186107868,
 0.09897433186107868,
 0.09897433186107867,
 0.09897433186107867,
 0.09874838622020375,
 0.09874838622020374,
 0.09847319278346617,
 0.09847319278346617,
 0.09847319278346617,
 0.09801960588196068,
 0.09801960588196067,
 0.09801960588196067,
 0.09797958971132711,
 0.09797958971132711,
 0.0975900072948533,
 0.0975900072948533,
 0.0975900072948533,
 0.0975900072948533,
 0.0975900072948533,
 0.09701425001453318,
 0.09701425001453318,
 0.09660917830792956,
 0.09630868246861535,
 0.09622504486493762,
 0.09622504486493762,
 0.0962250448649376,
 0.0962250448649376,
 0.09607689228305227,
 0.09607689228305227,
 0.09607689228305226,
 0.09607689228305226,
 0.09601587170383662,
 0.09578949441427993,
 0.09578949441427993,
 0.09525793444156803,
 0.09516619028617729,
 0.09516619028617729,
 0.09516619028617729,
 0.09491579957524988,
 0.09491579957524988,
 0.09428090415820634,
 0.09428090415820634,
 0.09428090415820632,
 0.09365858115816939,
 0.09341987329938274,
 0.09341987329938274,
 0.09341987329938274,
 0.09341987329938274,
 0.09333333333333331,
 0.0928414165097055,
 0.09271726499455304,
 0.09271726499455303,
 0.09271726499455303,
 0.09258200997725513,
 0.09258200997725513,
 0.09258200997725513,
 0.09245003270420485,
 0.09245003270420485,
 0.0923760430703401,
 0.0923760430703401,
 0.0917662935482247,
 0.0917662935482247,
 0.09152086306448586,
 0.09128709291752767,
 0.09128709291752767,
 0.09128709291752767,
 0.09128709291752767,
 0.09128709291752767,
 0.09128709291752767,
 0.09097176522946838,
 0.09097176522946838,
 0.09097176522946838,
 0.09097176522946838,
 0.09097176522946838,
 0.09058216273156765,
 0.09058216273156765,
 0.09019752336033947,
 0.09019752336033947,
 0.09019752336033945,
 0.09016696346674322,
 0.09016696346674322,
 0.09016696346674322,
 0.09016696346674322,
 0.09016696346674322,
 0.08944271909999156,
 0.08944271909999156,
 0.08944271909999156,
 0.0890870806374748,
 0.08908708063747478,
 0.08908708063747478,
 0.08888888888888889,
 0.08872139507342688,
 0.08870655251454873,
 0.08870655251454873,
 0.08870655251454873,
 0.08848020217749294,
 0.08804509063256237,
 0.08804509063256237,
 0.08804509063256237,
 0.08804509063256237,
 0.08804509063256237,
 0.08767140075192091,
 0.08728715609439693,
 0.08728715609439693,
 0.08728715609439693,
 0.08728715609439693,
 0.08703882797784891,
 0.08703882797784891,
 0.08703882797784891,
 0.08703882797784891,
 0.08703882797784891,
 0.08703882797784891,
 0.08703882797784891,
 0.08703882797784891,
 0.08665782448262419,
 0.08665782448262419,
 0.08660254037844387,
 0.08660254037844387,
 0.08660254037844385,
 0.08660254037844385,
 0.08660254037844385,
 0.08660254037844385,
 0.08606629658238703,
 0.08606629658238703,
 0.08606629658238703,
 0.08593378488473194,
 0.08593378488473194,
 0.08593378488473194,
 0.08576900278702358,
 0.08576900278702358,
 0.08576900278702357,
 0.08576900278702357,
 0.08576900278702357,
 0.08576900278702357,
 0.08576900278702357,
 0.08528028654224416,
 0.08512565307587486,
 0.08512565307587486,
 0.08512565307587484,
 0.08512565307587484,
 0.08512565307587484,
 0.08512565307587484,
 0.08512565307587484,
 0.08512565307587484,
 0.08464147390303178,
 0.08432740427115676,
 0.08432740427115676,
 0.08432740427115676,
 0.08432740427115676,
 0.08421519210665189,
 0.08421519210665189,
 0.08421519210665189,
 0.08421519210665188,
 0.08401680504168058,
 0.08401680504168058,
 0.08397822097303646,
 0.08340576562282989,
 0.08340576562282989,
 0.08340576562282989,
 0.08336878678455789,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08295613557843401,
 0.08295613557843401,
 0.08295613557843401,
 0.08292884288627292,
 0.08280786712108248,
 0.08280786712108248,
 0.08280786712108248,
 0.08280786712108248,
 0.08280786712108248,
 0.08247860988423222,
 0.08247860988423222,
 0.08247860988423222,
 0.08247860988423222,
 0.08247860988423222,
 0.08206945344647688,
 0.08206945344647688,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.08164965809277258,
 0.08164965809277258,
 0.08164965809277258,
 0.08164965809277258,
 0.08164965809277258,
 0.08164965809277258,
 0.08164965809277258,
 0.08164965809277258,
 0.08084520834544431,
 0.08053872662568291,
 0.08040302522073696,
 0.08040302522073696,
 0.08040302522073696,
 0.08040302522073696,
 0.08006407690254357,
 0.08006407690254355,
 0.08006407690254355,
 0.07999999999999999,
 0.07947194142390261,
 0.07947194142390261,
 0.07947194142390261,
 0.0794719414239026,
 0.07930515857181442,
 0.07930515857181442,
 0.07930515857181442,
 0.07930515857181442,
 0.07930515857181442,
 0.07930515857181442,
 0.07921180343813393,
 0.07921180343813393,
 0.07921180343813393,
 0.07921180343813393,
 0.07921180343813393,
 0.07895420339517226,
 0.07863570994927846,
 0.07856742013183861,
 0.07856742013183861,
 0.07856742013183861,
 0.07807200583588264,
 0.07807200583588264,
 0.07807200583588264,
 0.07807200583588264,
 0.07807200583588264,
 0.07807200583588264,
 0.07807200583588264,
 0.0779483762953957,
 0.0779483762953957,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07745966692414832,
 0.07745966692414832,
 0.07745966692414832,
 0.07745966692414832,
 0.07715167498104594,
 0.07715167498104594,
 0.07698003589195009,
 0.07698003589195009,
 0.07698003589195009,
 0.07650920556760057,
 0.07650920556760057,
 0.07650920556760057,
 0.07647191129018725,
 0.0759326396601999,
 0.0759326396601999,
 0.0759326396601999,
 0.0759326396601999,
 0.0759326396601999,
 0.0759326396601999,
 0.0759326396601999,
 0.0759326396601999,
 0.07580980435789032,
 0.07580980435789032,
 0.07580980435789032,
 0.07580980435789032,
 0.07580980435789032,
 0.07580980435789032,
 0.0757033298610225,
 0.07559289460184543,
 0.07559289460184543,
 0.07559289460184543,
 0.07559289460184543,
 0.07559289460184543,
 0.07516460280028289,
 0.07516460280028289,
 0.07516460280028289,
 0.07514691493021793,
 0.07492686492653551,
 0.07492686492653551,
 0.07492686492653551,
 0.07492686492653551,
 0.07492686492653551,
 0.07492686492653551,
 0.07453559924999296,
 0.07396002616336388,
 0.07396002616336388,
 0.07396002616336388,
 0.07396002616336388,
 0.07396002616336388,
 0.07392212709545727,
 0.07392212709545727,
 0.07392212709545727,
 0.07385489458759963,
 0.07385489458759963,
 0.07385489458759963,
 0.07385489458759963,
 0.07343880736345254,
 0.07332355751067664,
 0.07332355751067664,
 0.07332355751067664,
 0.07332355751067664,
 0.07302967433402213,
 0.07302967433402213,
 0.07302967433402213,
 0.07302967433402213,
 0.07273929674533078,
 0.07273929674533078,
 0.07273929674533078,
 0.07273929674533078,
 0.07273929674533078,
 0.07258661863112977,
 0.07223151185146151,
 0.07223151185146151,
 0.07223151185146151,
 0.07223151185146151,
 0.07223151185146151,
 0.07223151185146151,
 0.07223151185146151,
 0.07216878364870322,
 0.07213357077339458,
 0.07213357077339458,
 0.07213357077339458,
 0.07213357077339458,
 0.07213357077339458,
 0.07213357077339458,
 0.07213357077339458,
 0.07213357077339458,
 0.07184212081070995,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07126966450997983,
 0.07126966450997983,
 0.07126966450997983,
 0.07126966450997983,
 0.07126966450997983,
 0.07126966450997983,
 0.07126966450997983,
 0.07126966450997983,
 0.07108186533109107,
 0.07106690545187014,
 0.07106690545187014,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07053456158585981,
 0.07053456158585981,
 0.07053456158585981,
 0.0704360725060499,
 0.0704360725060499,
 0.0704360725060499,
 0.0704360725060499,
 0.0704360725060499,
 0.0704360725060499,
 0.07001400420140048,
 0.07001400420140047,
 0.0699854212223765,
 0.06963106238227913,
 0.06963106238227913,
 0.06963106238227913,
 0.06963106238227913,
 0.06963106238227913,
 0.06963106238227913,
 0.06963106238227913,
 0.06963106238227913,
 0.06950480468569158,
 0.06950480468569158,
 0.06950480468569158,
 0.06950480468569158,
 0.06928203230275508,
 0.06928203230275508,
 0.06928203230275508,
 0.06900655593423541,
 0.06900655593423541,
 0.06885303726590962,
 0.06885303726590962,
 0.06885303726590962,
 0.06885303726590962,
 0.06885303726590962,
 0.06885303726590962,
 0.06885303726590962,
 0.06885303726590962,
 0.06851887098275315,
 0.06851887098275315,
 0.06851887098275315,
 0.06826561487862891,
 0.06810052246069988,
 0.06810052246069988,
 0.06810052246069988,
 0.06810052246069988,
 0.06810052246069988,
 0.06804138174397717,
 0.06804138174397717,
 0.06793662204867573,
 0.06793662204867573,
 0.06793662204867573,
 0.06793662204867573,
 0.06793662204867573,
 0.06793662204867573,
 0.06793662204867573,
 0.06793662204867573,
 0.06737215368532151,
 0.06737215368532151,
 0.06737215368532151,
 0.06737215368532151,
 0.06737215368532151,
 0.06737215368532151,
 0.06737215368532151,
 0.06737215368532151,
 0.06711560552140243,
 0.0669774686623137,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666665,
 0.06666666666666665,
 0.06622661785325218,
 0.06598288790738578,
 0.06598288790738578,
 0.06598288790738578,
 0.06598288790738578,
 0.06598288790738578,
 0.06546536707079771,
 0.06546536707079771,
 0.0654653670707977,
 0.0654653670707977,
 0.0654653670707977,
 0.0654653670707977,
 0.0654653670707977,
 0.0654653670707977,
 0.0654653670707977,
 0.0654653670707977,
 0.0654653670707977,
 0.06537204504606133,
 0.06531972647421808,
 0.06531972647421808,
 0.06531972647421808,
 0.06531972647421808,
 0.06531972647421808,
 0.06495698024616309,
 0.06467616667635545,
 0.06467616667635545,
 0.06467616667635545,
 0.06467616667635545,
 0.06467616667635545,
 0.06467616667635545,
 0.06467616667635545,
 0.06454972243679027,
 0.06432675209026768,
 0.06432675209026768,
 0.06432675209026768,
 0.06405126152203484,
 0.06405126152203484,
 0.06405126152203484,
 0.06405126152203484,
 0.06405126152203484,
 0.06405126152203484,
 0.06375767130633381,
 0.06375767130633381,
 0.06351073488299556,
 0.06344412685745153,
 0.06344412685745153,
 0.06344412685745153,
 0.06344412685745153,
 0.06344412685745153,
 0.06344412685745153,
 0.06337242505244778,
 0.06324555320336757,
 0.06324555320336757,
 0.06324555320336757,
 0.06324555320336757,
 0.06324555320336757,
 0.06324555320336757,
 0.06324555320336757,
 0.06324555320336757,
 0.06324555320336757,
 0.06324555320336757,
 0.06324555320336757,
 0.06324555320336757,
 0.0629940788348712,

In [84]:
list(enumerate(similarity[0]))

[(0, 0.9999999999999991),
 (1, 0.06885303726590962),
 (2, 0.04948716593053934),
 (3, 0.02275520495954297),
 (4, 0.31035207097778317),
 (5, 0.14907119849998593),
 (6, 0.023570226039551584),
 (7, 0.13093073414159542),
 (8, 0.039605901719066965),
 (9, 0.07516460280028289),
 (10, 0.10444659357341869),
 (11, 0.06737215368532151),
 (12, 0.055470019622522904),
 (13, 0.02684624220856097),
 (14, 0.1281025230440697),
 (15, 0.043994134506405984),
 (16, 0.10434983894999016),
 (17, 0.11120768749710652),
 (18, 0.12701705922171763),
 (19, 0.07053456158585981),
 (20, 0.03380617018914066),
 (21, 0.050529115263991134),
 (22, 0.04364357804719846),
 (23, 0.055470019622522904),
 (24, 0.04548588261473419),
 (25, 0.0669774686623137),
 (26, 0.17126976771553504),
 (27, 0.1963961012123931),
 (28, 0.07106690545187014),
 (29, 0.056853524361496106),
 (30, 0.08870655251454873),
 (31, 0.15032920560056579),
 (32, 0.06666666666666665),
 (33, 0.07807200583588264),
 (34, 0.0),
 (35, 0.1811643254631353),
 (36, 0.16329931618554516),
 (37, 0.08703882797784891),
 (38, 0.03897418814769785),
 (39, 0.09701425001453318),
 (40, 0.03265986323710904),
 (41, 0.17888543819998312),
 (42, 0.0),
 (43, 0.09097176522946838),
 (44, 0.04020151261036848),
 (45, 0.07001400420140048),
 (46, 0.18856180831641264),
 (47, 0.3197221015541812),
 (48, 0.08944271909999156),
 (49, 0.03903600291794132),
 (50, 0.07396002616336388),
 (51, 0.08872139507342688),
 (52, 0.24743582965269673),
 (53, 0.11925695879998875),
 (54, 0.020412414523193145),
 (55, 0.048154341234307674),
 (56, 0.24886840673530203),
 (57, 0.07213357077339458),
 (58, 0.0305887645160749),
 (59, 0.05954913341754135),
 (60, 0.014907119849998594),
 (61, 0.23190036174568107),
 (62, 0.048154341234307674),
 (63, 0.06950480468569158),
 (64, 0.04898979485566356),
 (65, 0.03333333333333333),
 (66, 0.015430334996209188),
 (67, 0.20083160441856088),
 (68, 0.07930515857181442),
 (69, 0.044861772327363526),
 (70, 0.12185435916898847),
 (71, 0.06963106238227913),
 (72, 0.11790126894931265),
 (73, 0.019802950859533482),
 (74, 0.2578013546541959),
 (75, 0.07492686492653551),
 (76, 0.06666666666666667),
 (77, 0.019730544946679602),
 (78, 0.031139957766460915),
 (79, 0.07516460280028289),
 (80, 0.01924500897298752),
 (81, 0.08206945344647688),
 (82, 0.08512565307587484),
 (83, 0.23791547571544322),
 (84, 0.08767140075192091),
 (85, 0.07258661863112977),
 (86, 0.09128709291752767),
 (87, 0.17407765595569782),
 (88, 0.04714045207910316),
 (89, 0.049147318718299034),
 (90, 0.03698001308168194),
 (91, 0.20604887854797269),
 (92, 0.04548588261473419),
 (93, 0.04548588261473419),
 (94, 0.28097574347450816),
 (95, 0.2570358257720839),
 (96, 0.07396002616336388),
 (97, 0.07930515857181442),
 (98, 0.054100178080045934),
 (99, 0.01601281538050871),
 (100, 0.07071067811865475),
 (101, 0.14907119849998593),
 (102, 0.11731769201708263),
 (103, 0.08660254037844387),
 (104, 0.031722063428725765),
 (105, 0.09128709291752767),
 (106, 0.03999999999999999),
 (107, 0.10527227119356301),
 (108, 0.17320508075688773),
 (109, 0.06324555320336757),
 (110, 0.12792042981336624),
 (111, 0.18257418583505536),
 (112, 0.08703882797784891),
 (113, 0.031139957766460915),
 (114, 0.029814239699997188),
 (115, 0.06405126152203484),
 (116, 0.050529115263991134),
 (117, 0.0305887645160749),
 (118, 0.010454167469786332),
 (119, 0.058621038176054914),
 (120, 0.0),
 (121, 0.05694947974514993),
 (122, 0.07921180343813393),
 (123, 0.10079052613579391),
 (124, 0.07332355751067664),
 (125, 0.08040302522073696),
 (126, 0.061721339984836754),
 (127, 0.13617658132983798),
 (128, 0.01951800145897066),
 (129, 0.08593378488473194),
 (130, 0.015161960871578064),
 (131, 0.09016696346674322),
 (132, 0.04296689244236597),
 (133, 0.050529115263991134),
 (134, 0.07807200583588264),
 (135, 0.0),
 (136, 0.015569978883230457),
 (137, 0.02275520495954297),
 (138, 0.08908708063747478),
 (139, 0.0699854212223765),
 (140, 0.04296689244236597),
 (141, 0.1951800145897066),
 (142, 0.0547722557505166),
 (143, 0.06804138174397717),
 (144, 0.06375767130633381),
 (145, 0.08292884288627292),
 (146, 0.034299717028501764),
 (147, 0.09999999999999999),
 (148, 0.05855400437691198),
 (149, 0.30772872744833174),
 (150, 0.24377011365784199),
 (151, 0.0962250448649376),
 (152, 0.036514837167011066),
 (153, 0.05443310539518173),
 (154, 0.01951800145897066),
 (155, 0.013245323570650435),
 (156, 0.15701620314577236),
 (157, 0.06324555320336757),
 (158, 0.32005290567945544),
 (159, 0.05855400437691198),
 (160, 0.05773502691896256),
 (161, 0.06221710168382551),
 (162, 0.061237243569579436),
 (163, 0.07273929674533078),
 (164, 0.05694947974514993),
 (165, 0.059628479399994376),
 (166, 0.0975900072948533),
 (167, 0.04364357804719846),
 (168, 0.16666666666666666),
 (169, 0.13856406460551016),
 (170, 0.07273929674533078),
 (171, 0.055470019622522904),
 (172, 0.08333333333333333),
 (173, 0.016169041669088863),
 (174, 0.1018350154434631),
 (175, 0.030065841120113155),
 (176, 0.014433756729740642),
 (177, 0.024077170617153837),
 (178, 0.016666666666666666),
 (179, 0.04618802153517006),
 (180, 0.014106912317171963),
 (181, 0.013333333333333329),
 (182, 0.07580980435789032),
 (183, 0.059234887775909226),
 (184, 0.30076824709656186),
 (185, 0.09897433186107867),
 (186, 0.034299717028501764),
 (187, 0.08804509063256237),
 (188, 0.04738791022072738),
 (189, 0.049236596391733084),
 (190, 0.06337242505244778),
 (191, 0.04472135954999578),
 (192, 0.05773502691896257),
 (193, 0.07161148740394328),
 (194, 0.015861031714362882),
 (195, 0.03606678538669729),
 (196, 0.08703882797784891),
 (197, 0.044353276257274366),
 (198, 0.033686076842660756),
 (199, 0.07999999999999999),
 (200, 0.14985372985307102),
 (201, 0.019802950859533482),
 (202, 0.01951800145897066),
 (203, 0.08703882797784891),
 (204, 0.01529438225803745),
 (205, 0.039605901719066965),
 (206, 0.1128552985373757),
 (207, 0.1352962850405092),
 (208, 0.15894388284780522),
 (209, 0.017817416127494958),
 (210, 0.028426762180748053),
 (211, 0.047583095143088644),
 (212, 0.05009794328681195),
 (213, 0.061545745489666355),
 (214, 0.015569978883230457),
 (215, 0.10811798054391773),
 (216, 0.03796631983009995),
 (217, 0.06950480468569158),
 (218, 0.02581988897471611),
 (219, 0.05855400437691198),
 (220, 0.13926212476455826),
 (221, 0.016169041669088863),
 (222, 0.1710674406895399),
 (223, 0.15322617553657472),
 (224, 0.05560384374855326),
 (225, 0.04803844614152614),
 (226, 0.07213357077339458),
 (227, 0.08333333333333333),
 (228, 0.22417941532712196),
 (229, 0.136176581329838),
 (230, 0.1986798535597565),
 (231, 0.02909571869813231),
 (232, 0.14426714154678913),
 (233, 0.17457431218879385),
 (234, 0.04026936331284146),
 (235, 0.036514837167011066),
 (236, 0.19882696935448685),
 (237, 0.03903600291794132),
 (238, 0.09903751369442765),
 (239, 0.30792014356780034),
 (240, 0.030323921743156127),
 (241, 0.0547722557505166),
 (242, 0.06467616667635545),
 (243, 0.06711560552140243),
 (244, 0.03442651863295481),
 (245, 0.04364357804719846),
 (246, 0.09152086306448586),
 (247, 0.0),
 (248, 0.027029495135979433),
 (249, 0.15009575487729127),
 (250, 0.0),
 (251, 0.07223151185146151),
 (252, 0.012451456127293804),
 (253, 0.10393116839386092),
 (254, 0.04850712500726659),
 (255, 0.0),
 (256, 0.09901475429766741),
 (257, 0.060647843486312254),
 (258, 0.02909571869813231),
 (259, 0.03265986323710904),
 (260, 0.28323527714997326),
 (261, 0.04296689244236597),
 (262, 0.04850712500726659),
 (263, 0.05940885257860044),
 (264, 0.0),
 (265, 0.017407765595569783),
 (266, 0.0816496580927726),
 (267, 0.08164965809277258),
 (268, 0.014664711502135327),
 (269, 0.016843038421330378),
 (270, 0.2236067977499789),
 (271, 0.10327955589886444),
 (272, 0.02010075630518424),
 (273, 0.010721125348377946),
 (274, 0.05985056016645797),
 (275, 0.10690449676496974),
 (276, 0.03698001308168194),
 (277, 0.041702882811414946),
 (278, 0.3500700210070024),
 (279, 0.1352962850405092),
 (280, 0.0),
 (281, 0.04026936331284146),
 (282, 0.04296689244236597),
 (283, 0.0),
 (284, 0.013333333333333329),
 (285, 0.013900960937138315),
 (286, 0.024759378423606912),
 (287, 0.030323921743156127),
 (288, 0.017609018126512475),
 (289, 0.032338083338177726),
 (290, 0.03606678538669729),
 (291, 0.06810052246069988),
 (292, 0.0704360725060499),
 (293, 0.017609018126512475),
 (294, 0.0759326396601999),
 (295, 0.06227991553292183),
 (296, 0.036115755925730755),
 (297, 0.060647843486312254),
 (298, 0.0),
 (299, 0.023448415270421966),
 (300, 0.33626912299068296),
 (301, 0.14026687687393438),
 (302, 0.04020151261036848),
 (303, 0.016169041669088863),
 (304, 0.08336878678455789),
 (305, 0.33975790709773834),
 (306, 0.1951800145897066),
 (307, 0.08848020217749294),
 (308, 0.033686076842660756),
 (309, 0.04216370213557838),
 (310, 0.02970442628930022),
 (311, 0.11208970766356098),
 (312, 0.10105823052798227),
 (313, 0.042884501393511784),
 (314, 0.0),
 (315, 0.05694947974514993),
 (316, 0.043994134506405984),
 (317, 0.04444444444444444),
 (318, 0.0),
 (319, 0.06666666666666667),
 (320, 0.1005037815259212),
 (321, 0.0),
 (322, 0.25855725062711327),
 (323, 0.039605901719066965),
 (324, 0.016495721976846445),
 (325, 0.05619514869490163),
 (326, 0.052223296786709346),
 (327, 0.03265986323710904),
 (328, 0.0),
 (329, 0.10444659357341869),
 (330, 0.10690449676496976),
 (331, 0.041702882811414946),
 (332, 0.08247860988423222),
 (333, 0.09271726499455304),
 (334, 0.09999999999999999),
 (335, 0.06666666666666667),
 (336, 0.031139957766460915),
 (337, 0.046291004988627565),
 (338, 0.039605901719066965),
 (339, 0.03521803625302495),
 (340, 0.033686076842660756),
 (341, 0.07213357077339458),
 (342, 0.19157898882855987),
 (343, 0.012909944487358055),
 (344, 0.018257418583505533),
 (345, 0.015569978883230457),
 (346, 0.0),
 (347, 0.03405026123034994),
 (348, 0.04020151261036848),
 (349, 0.055470019622522904),
 (350, 0.050529115263991134),
 (351, 0.0),
 (352, 0.01924500897298752),
 (353, 0.04232073695151589),
 (354, 0.0),
 (355, 0.034815531191139566),
 (356, 0.05282705437953742),
 (357, 0.0),
 (358, 0.05619514869490163),
 (359, 0.020412414523193145),
 (360, 0.07650920556760057),
 (361, 0.03333333333333333),
 (362, 0.12326312688558731),
 (363, 0.11547005383792516),
 (364, 0.014547859349066154),
 (365, 0.1411300658019085),
 (366, 0.06531972647421808),
 (367, 0.01632993161855452),
 (368, 0.07807200583588264),
 (369, 0.04670993664969137),
 (370, 0.06885303726590962),
 (371, 0.11430952132988163),
 (372, 0.06737215368532151),
 (373, 0.3829708431025352),
 (374, 0.028213824634343927),
 (375, 0.05773502691896257),
 (376, 0.044353276257274366),
 (377, 0.0),
 (378, 0.0),
 (379, 0.04573295603800235),
 (380, 0.015569978883230457),
 (381, 0.05298129428260174),
 (382, 0.0),
 (383, 0.02956885083818291),
 (384, 0.03142696805273544),
 (385, 0.03903600291794132),
 (386, 0.01370377419655063),
 (387, 0.014106912317171963),
 (388, 0.0),
 (389, 0.13862065601673437),
 (390, 0.017817416127494958),
 (391, 0.07343880736345254),
 (392, 0.01702513061517497),
 (393, 0.01601281538050871),
 (394, 0.014907119849998594),
 (395, 0.05443310539518173),
 (396, 0.013801311186847081),
 (397, 0.03442651863295481),
 (398, 0.0),
 (399, 0.015430334996209188),
 (400, 0.10820035616009185),
 (401, 0.15491933384829665),
 (402, 0.030860669992418377),
 (403, 0.0629940788348712),
 (404, 0.10690449676496974),
 (405, 0.014322297480788657),
 (406, 0.026666666666666658),
 (407, 0.060647843486312254),
 (408, 0.020739033894608502),
 (409, 0.0),
 (410, 0.06351073488299556),
 (411, 0.04803844614152614),
 (412, 0.10613372610104645),
 (413, 0.10613372610104645),
 (414, 0.01924500897298752),
 (415, 0.06324555320336757),
 (416, 0.04714045207910316),
 (417, 0.03849001794597504),
 (418, 0.09428090415820634),
 (419, 0.10999438818457405),
 (420, 0.11120768749710652),
 (421, 0.0),
 (422, 0.12060453783110543),
 (423, 0.06227991553292183),
 (424, 0.025660011963983362),
 (425, 0.050697940041958225),
 (426, 0.06189844605901728),
 (427, 0.01924500897298752),
 (428, 0.03380617018914066),
 (429, 0.0),
 (430, 0.12333396776895567),
 (431, 0.01571348402636772),
 (432, 0.24731360893412463),
 (433, 0.01951800145897066),
 (434, 0.0),
 (435, 0.02108185106778919),
 (436, 0.016843038421330378),
 (437, 0.01849000654084097),
 (438, 0.035634832254989916),
 (439, 0.05282705437953742),
 (440, 0.016666666666666666),
 (441, 0.03606678538669729),
 (442, 0.038023455031468666),
 (443, 0.04472135954999578),
 (444, 0.013423121104280485),
 (445, 0.032338083338177726),
 (446, 0.060647843486312254),
 (447, 0.015032920560056577),
 (448, 0.07580980435789032),
 (449, 0.055470019622522904),
 (450, 0.030065841120113155),
 (451, 0.015430334996209188),
 (452, 0.011785113019775792),
 (453, 0.01571348402636772),
 (454, 0.20207259421636903),
 (455, 0.015861031714362882),
 (456, 0.14765433214708534),
 (457, 0.0547722557505166),
 (458, 0.031139957766460915),
 (459, 0.09622504486493762),
 (460, 0.06885303726590962),
 (461, 0.3618136134933163),
 (462, 0.09578949441427993),
 (463, 0.06221710168382551),
 (464, 0.0),
 (465, 0.025197631533948477),
 (466, 0.14517323726225953),
 (467, 0.06227991553292183),
 (468, 0.017609018126512475),
 (469, 0.06851887098275315),
 (470, 0.04803844614152614),
 (471, 0.04948716593053934),
 (472, 0.06963106238227913),
 (473, 0.13645764784420258),
 (474, 0.0),
 (475, 0.06950480468569158),
 (476, 0.08728715609439693),
 (477, 0.0),
 (478, 0.04618802153517005),
 (479, 0.06454972243679027),
 (480, 0.1281025230440697),
 (481, 0.01632993161855452),
 (482, 0.016843038421330378),
 (483, 0.1518652793203998),
 (484, 0.042884501393511784),
 (485, 0.04714045207910316),
 (486, 0.03671940368172627),
 (487, 0.12649110640673514),
 (488, 0.059234887775909226),
 (489, 0.0),
 (490, 0.13856406460551016),
 (491, 0.07745966692414832),
 (492, 0.06030226891555272),
 (493, 0.024902912254587607),
 (494, 0.02108185106778919),
 (495, 0.1366260102127946),
 (496, 0.028426762180748053),
 (497, 0.0),
 (498, 0.039605901719066965),
 (499, 0.0),
 (500, 0.015861031714362882),
 (501, 0.047639306734033084),
 (502, 0.2618614682831908),
 (503, 0.049999999999999996),
 (504, 0.0),
 (505, 0.1366260102127946),
 (506, 0.06221710168382551),
 (507, 0.32118202741878643),
 (508, 0.08247860988423222),
 (509, 0.016666666666666666),
 (510, 0.08421519210665189),
 (511, 0.07492686492653551),
 (512, 0.08703882797784891),
 (513, 0.06344412685745153),
 (514, 0.028867513459481284),
 (515, 0.033686076842660756),
 (516, 0.014784425419091455),
 (517, 0.05560384374855326),
 (518, 0.034815531191139566),
 (519, 0.0),
 (520, 0.0),
 (521, 0.014784425419091455),
 (522, 0.0),
 (523, 0.034815531191139566),
 (524, 0.10444659357341869),
 (525, 0.04714045207910316),
 (526, 0.04714045207910316),
 (527, 0.0),
 (528, 0.014664711502135327),
 (529, 0.12049281521534184),
 (530, 0.0654653670707977),
 (531, 0.09801960588196067),
 (532, 0.08397822097303646),
 (533, 0.04618802153517006),
 (534, 0.07559289460184543),
 (535, 0.09607689228305226),
 (536, 0.07856742013183861),
 (537, 0.045291081365783824),
 (538, 0.0),
 (539, 0.2809757434745082),
 (540, 0.03202563076101742),
 (541, 0.26222491255009456),
 (542, 0.039735970711951306),
 (543, 0.05163977794943222),
 (544, 0.03442651863295481),
 (545, 0.03202563076101742),
 (546, 0.04364357804719846),
 (547, 0.05940885257860044),
 (548, 0.015032920560056577),
 (549, 0.2405267289609052),
 (550, 0.017407765595569783),
 (551, 0.02684624220856097),
 (552, 0.0),
 (553, 0.018731716231633878),
 (554, 0.0),
 (555, 0.03188964020716403),
 (556, 0.08512565307587486),
 (557, 0.21602468994692864),
 (558, 0.03698001308168194),
 (559, 0.04020151261036848),
 (560, 0.028213824634343927),
 (561, 0.018983159915049976),
 (562, 0.0),
 (563, 0.01601281538050871),
 (564, 0.17432038578211329),
 (565, 0.043994134506405984),
 (566, 0.012909944487358055),
 (567, 0.018257418583505533),
 (568, 0.11790126894931265),
 (569, 0.0305887645160749),
 (570, 0.042884501393511784),
 (571, 0.09847319278346617),
 (572, 0.051006137045067054),
 (573, 0.012751534261266762),
 (574, 0.014547859349066154),
 (575, 0.07784989441615228),
 (576, 0.016495721976846445),
 (577, 0.2613098319673951),
 (578, 0.029329423004270654),
 (579, 0.16169041669088863),
 (580, 0.014213381090374027),
 (581, 0.2613098319673951),
 (582, 0.2933333333333333),
 (583, 0.043994134506405984),
 (584, 0.05601120336112038),
 (585, 0.09258200997725513),
 (586, 0.1001958865736239),
 (587, 0.14433756729740646),
 (588, 0.018731716231633878),
 (589, 0.10886621079036347),
 (590, 0.020739033894608502),
 (591, 0.07332355751067664),
 (592, 0.13645764784420258),
 (593, 0.04232073695151589),
 (594, 0.02956885083818291),
 (595, 0.2333333333333333),
 (596, 0.05913770167636582),
 (597, 0.03142696805273544),
 (598, 0.04618802153517006),
 (599, 0.1259673314595547),
 (600, 0.047583095143088644),
 (601, 0.041816669879145334),
 (602, 0.029814239699997188),
 (603, 0.031139957766460915),
 (604, 0.03903600291794132),
 (605, 0.0),
 (606, 0.02581988897471611),
 (607, 0.08340576562282989),
 (608, 0.0),
 (609, 0.04111132258965189),
 (610, 0.0779483762953957),
 (611, 0.06013168224022631),
 (612, 0.05913770167636582),
 (613, 0.020739033894608502),
 (614, 0.03265986323710904),
 (615, 0.014784425419091455),
 (616, 0.0),
 (617, 0.15320646925708528),
 (618, 0.07745966692414832),
 (619, 0.0),
 (620, 0.0),
 (621, 0.052223296786709346),
 (622, 0.01370377419655063),
 (623, 0.015430334996209188),
 (624, 0.12060453783110545),
 (625, 0.04948716593053934),
 (626, 0.18683974659876548),
 (627, 0.08606629658238703),
 (628, 0.14770978917519925),
 (629, 0.029329423004270654),
 (630, 0.01529438225803745),
 (631, 0.023570226039551584),
 (632, 0.08804509063256237),
 (633, 0.10393116839386093),
 (634, 0.06810052246069988),
 (635, 0.10183501544346309),
 (636, 0.015569978883230457),
 (637, 0.04898979485566356),
 (638, 0.04020151261036848),
 (639, 0.0),
 (640, 0.03265986323710904),
 (641, 0.0),
 (642, 0.14784425419091457),
 (643, 0.18856180831641267),
 (644, 0.03405026123034994),
 (645, 0.02780192187427663),
 (646, 0.049999999999999996),
 (647, 0.05865884600854131),
 (648, 0.01702513061517497),
 (649, 0.0),
 (650, 0.01529438225803745),
 (651, 0.0),
 (652, 0.014784425419091455),
 (653, 0.07921180343813393),
 (654, 0.058621038176054914),
 (655, 0.04898979485566356),
 (656, 0.014907119849998594),
 (657, 0.04618802153517005),
 (658, 0.041702882811414946),
 (659, 0.015161960871578064),
 (660, 0.10721125348377948),
 (661, 0.2684624220856097),
 (662, 0.0),
 (663, 0.0),
 (664, 0.03698001308168194),
 (665, 0.04588314677411235),
 (666, 0.10215078369104982),
 (667, 0.0),
 (668, 0.03903600291794132),
 (669, 0.020739033894608502),
 (670, 0.029382126412463502),
 (671, 0.046291004988627565),
 (672, 0.03299144395369289),
 (673, 0.039735970711951306),
 (674, 0.06963106238227913),
 (675, 0.05009794328681195),
 (676, 0.017213259316477405),
 (677, 0.08401680504168058),
 (678, 0.04020151261036848),
 (679, 0.0),
 (680, 0.17284832429004493),
 (681, 0.03606678538669729),
 (682, 0.014322297480788657),
 (683, 0.031139957766460915),
 (684, 0.041478067789217005),
 (685, 0.021442250696755892),
 (686, 0.037463432463267755),
 (687, 0.11094003924504581),
 (688, 0.04296689244236597),
 (689, 0.0),
 (690, 0.02581988897471611),
 (691, 0.06598288790738578),
 (692, 0.24731360893412466),
 (693, 0.0),
 (694, 0.025982792098465234),
 (695, 0.049999999999999996),
 (696, 0.013245323570650435),
 (697, 0.0),
 (698, 0.014784425419091455),
 (699, 0.0),
 (700, 0.01601281538050871),
 (701, 0.06324555320336757),
 (702, 0.01223980122724209),
 (703, 0.012991396049232617),
 (704, 0.09607689228305227),
 (705, 0.015161960871578064),
 (706, 0.01632993161855452),
 (707, 0.0),
 (708, 0.015861031714362882),
 (709, 0.04200840252084029),
 (710, 0.04026936331284146),
 (711, 0.03796631983009995),
 (712, 0.013900960937138315),
 (713, 0.049518756847213824),
 (714, 0.0),
 (715, 0.06324555320336757),
 (716, 0.02222222222222222),
 (717, 0.0),
 (718, 0.04111132258965189),
 (719, 0.0),
 (720, 0.03202563076101742),
 (721, 0.019802950859533482),
 (722, 0.0),
 (723, 0.027602622373694163),

In [85]:
def recommend(movie):
    movie_index = movies[movies['title']== movie].index[0]
    distance = similarity[movie_index]
    
    movies_list = sorted(list(enumerate(distance)),reverse = True, key = lambda x:x[1])[1:6]

    recommended_movies=[]
    for i in movies_list:
        recommended_movies.append(movies.iloc[i[0]].title)
    return recommended_movies

In [86]:
recommend('Avatar')

['Aliens', 'Moonraker', 'Alien', 'Alien³', 'Silent Running']

In [87]:
new_df.iloc[539].title

'Titan A.E.'

In [88]:
sorted(list(enumerate(similarity[0])),reverse = True, key = lambda x:x[1])[1:6]

[(2405, 0.4839354795704658),
 (1533, 0.4335521648830699),
 (3160, 0.4278406467922595),
 (838, 0.398216086792002),
 (4336, 0.3920784235278427)]

In [89]:
new_df[new_df['title']=="Batman Begins"].index[0]

119

In [90]:
import pickle

In [91]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl', 'wb'))

In [92]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [94]:
pickle.dump(similarity,open('similarity.pkl', 'wb'))